version: "3.9"
services:
  nextjs-client:
    build: ./nextjs-client
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./nextjs-client/pages:/app/pages
      - ./nextjs-client/public:/app/public
      - ./nextjs-client/styles:/app/styles
      - ./nextjs-client/package.json:/app/package.json
      - ./nextjs-client/package-lock.json:/app/package-lock.json
      - ./nextjs-client/tsconfig.json:/app/tsconfig.json
      - ./nextjs-client/globals.d.ts:/app/globals.d.ts
  graphql:
    extends: 
      file: ./graphql/docker-compose.module.yml
      service: graphql
  migrate:
    extends: 
      file: ./migrate/docker-compose.module.yml
      service: migrate
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: dev_overview
      POSTGRES_PASSWORD: devpassword
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8100:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dev.com
      PGADMIN_DEFAULT_PASSWORD: pgadmindev