version: "3.9"
services:
  nextjs:
    extends: 
      file: ./nextjs/docker-compose.module.yml
      service: nextjs
  api:
    extends: 
      file: ./api/docker-compose.module.yml
      service: api
  # graphql:
  #   extends: 
  #     file: ./graphql/docker-compose.module.yml
  #     service: graphql
  migrate:
    extends: 
      file: ./migrate/docker-compose.module.yml
      service: migrate
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: devpassword
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8100:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dev.com
      PGADMIN_DEFAULT_PASSWORD: pgadmindev